### ISSUE TITLE
Segmentation fault with --probThreshold 0

### ISSUE THREAD

**Issue by hguturu** [statgen/Minimac4#17]
https://github.com/statgen/Minimac4/blob/0a0a5b1ffef362485d0cc683976cda6e767f1deb/src/MarkovModel.cpp#L704

I believe its due to this line where this loop runs due to `NoBestMatchFullRefHaps` being unintialized and tries to access values in the matrix `BestMatchFullRefHaps` which has not been initialized when `--probThreshold 0`.

An additional confirmation - To turn off all approximation we need to do `--probThreshold 0 --diffThreshold 0 --topThreshold 0`, right? Not sure if there are other similar issues with the no approximation path due to uninitialized values being used.

**Comment by Santy-8128** [comment]
Hi Harendra,

Thanks for pointing this out. You are correct. Your pull request fixes this issue and I will also try to look at if there are any other situations where this can happen. Thanks a lot !

**Comment by hguturu** [comment]
Submitted a new pull request #19 to handle this segfault issue and properly compute the dosage values.
