### ISSUE TITLE
Undefined behavior in HaplotypeSet::reconstructHaplotype

### ISSUE THREAD

**Issue by jonathonl** [statgen/Minimac4#2]
https://github.com/statgen/Minimac4/blob/990cf62d671397307216adac4351f74600b95589/src/HaplotypeSet.cpp#L527
The logic on this line is problematic. There's no guarantee as to whether the leftmost access to 'reHaplotypes' will be pre or post increment of 'markerIndex', and it's unclear to me what the desired behavior is supposed to be.

**Comment by Santy-8128** [comment]
That is correct. I can't believe that never gave a segFault. I will update
that tonight, or you can fix that on the git if you want.

*Regards,*
*Sayantan Das,*



*Post-Doctoral Fellow Department of BiostatisticsUniversity of Michigan,
Ann Arbor.MI 48109-2029*
