### ISSUE TITLE
Allowing chomosome number above 22

### ISSUE THREAD

**Issue by ChrisINRA** [statgen/Minimac4#27]
Hi,
Thanks a lot for developing minimac4.
I used Minimac2 few years ago and I'm impressed with the improvement in computing time.

Still, I have a minor problem.
I'm working in cattle which have 29 chromosome (+ X and Y).  I was able to convert my data to M3vcf files (using --chr option)  but now I cannot run imputation for chromosome 23 and above.

"GWAS VCF File contains chromosome : 29
 VCF File can only contain chromosomes 1-22, X(23), Y(24) !!! "

Is there an option to allow imputation on chromosome 29 for eg ?

Thanks in advance,

Chris

**Comment by yukt** [comment]
Hi Chris,

There is a latent option --MyChromosome in minimac4 that accommodates your needs. Please try adding "--MyChromosome 29” into your command line.

Best,

Ketian

**Comment by ChrisINRA** [comment]
It worked !  Thanks a lot.
I looked twice on the doc but wasn't able to find the option.

**Comment by Santy-8128** [comment]
Please use the hidden option --myChromosome 29 for it to work.


*Regards,*
Sayantan Das,

*23andMe*
