### ISSUE TITLE
Option to Subset Samples in Reference Panel

### ISSUE THREAD

**Issue by jonathonl** [statgen/Minimac4#28]
It would be nice to subset the reference panel on the fly by simply adding a parameter to minimac4 (e.g. —refSamples - file with all the sample IDs to use).

**Comment by sarahgra** [comment]
Has this option been implemented yet? It seems like it would also be very helpful if the topmed imputation server could automatically identify participants overlapping between the input dataset and the reference panel to automatically exclude them?

**Comment by jonathonl** [comment]
As of v4.1, you can specify a keep list with the `--sample-ids-file` option. There are no plans to automatically exclude though.  I'm assuming you mean exclude the samples from the reference panel. It would be computationally inefficient to recompress the reference haplotype structure for every match encountered.
