### ISSUE TITLE
How should missing genotypes be represented in prephased data?

### ISSUE THREAD

**Issue by biona001** [statgen/Minimac4#31]
I know that Minimac4's target genotypes files should be phased (so using `|` as allele separators for GT field in the `vcf` file). However, should the missing data be `.|.` or `.\.` or something else? 

For instance, if I simulate 100 sample's complete genotype (phase known) and mask 1% of the entries (represented by `.\.`), would this file be "acceptable" for Minimac4?

**Comment by jonathonl** [comment]
Missing data in the array genotypes are usually imputed during phasing.

**Comment by Santy-8128** [comment]
Minimac4 is suitable only when large panels are used. It uses some
approximations that might not give good accuracy in smaller panels. For
small panels (less than HRC) please use minimac3 if possible.

*Regards,*
Sayantan Das,

*23andMe*

**Comment by biona001** [comment]
Thank you both. According to @jonathonl this must mean Minimac 4 (and 3 also?) will change the phased entries? So observed entries in my original (unphased) data may not be preserved?

**Comment by Santy-8128** [comment]
Yes correct.
