### ISSUE TITLE
CMake Error occurred at installing minimac4

### ISSUE THREAD

**Issue by awakumaya** [statgen/Minimac4#36]
Hi,

When I did 'bash install.sh' for installing minimac4, as mentioned in README.md, the below error occurred.
How should I do to solve this trouble?
Please tell me any solutions or suggestion.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
STATGEN_LIBRARY
    linked by target "minimac4" in directory /home/awata/Minimac4

-- Configuring incomplete, errors occurred!
```

**Comment by jonathonl** [comment]
You should find more information on why the build failed in`install.log`.

**Comment by awakumaya** [comment]
Tha install.log is the below:

```
make: *** No targets specified and no makefile found.  Stop.
Binary created at /release-build/minimac4
(base) awata@MKI991866-B65:~/Minimac4$ cat install.log
Downloading https://zlib.net/zlib-1.2.11.tar.gz
Unexpected error: <class 'urllib.error.URLError'>
<urlopen error http protocol error: bad status line>
Failed to build package zlib
```

But zlib-1.2.11 has already be installed on my PC. How should I do?

**Comment by jonathonl** [comment]
Is it possible that you are blocked from external IPs on the machine you are trying to build on? If you can't use cget (which needs the internet), then you will have to install the libstatgen dependency (https://github.com/statgen/libStatGen) manually, before building Minimac 4 with cmake.

**Comment by awakumaya** [comment]
No. My PC is on internet because "apt update" and "apt upgrade" work on the PC. But internet connection seems to have any affects to build it. The above log message was on my home internet. And the below log message is on a proxy environment. 
```
Downloading https://zlib.net/zlib-1.2.11.tar.gz
Download failed with error 400 for: //zlib.net/zlib-1.2.11.tar.gz
Failed to build package zlib
```

And, I've already tried to install libstatgen from the github. The installation using 'make' finished without any errors but the following command 'make test' result in an error:
```
inputFileTest: InputFileTest.cpp:697: void IFILE_Test::test_ifread_ifgetc(const char*): Assertion `numBytesRead == DEFAULT_BUFFER_SIZE + 3' failed.
Aborted (core dumped)
../../../Makefiles/Makefile.test:53: recipe for target 'test' failed
make[3]: *** [test] Error 134
Makefile:24: recipe for target 'inputFileTest' failed
make[2]: *** [inputFileTest] Error 2
../Makefiles/Makefile.common:99: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/home/awata/libStatGen/general'
Makefiles/Makefile.base:15: recipe for target 'general' failed
make: *** [general] Error 2
```
So, I'm not sure the installation was done successfully. Anyway, I tried to install Minimac4 after installing libstatgen but the same error occurred.

**Comment by jonathonl** [comment]
if you have zlib and libStatGen installed in standard locations (you will need to run `sudo make install` in libStatGen directory), then you can build Minimac 4 by running:
```shell
mkdir build; cd build
cmake ..   # This step will fail if dependencies cannot be found.
make
```

Do not use `install.sh`.

**Comment by awakumaya** [comment]
Sorry. I couldn't to try the install again because I didn't have time to do it. Anyway, when I tried again using "cget install", not using "install.sh", the install was done without any errors. And test analysis using minimac4 succeeded. Thank you.
