### ISSUE TITLE
SNP ID format of input files and reference panels for imputation

### ISSUE THREAD

**Issue by jerrywzy** [statgen/Minimac4#43]
Hi there,

I am currently working on performing genotype imputation using a mixture of reference panels and input files on Minimac4. I have some previously completed imputation using input VCFs where the SNP IDs have been reannotated, so that the IDs follow the format of CHR:POS:REF:ALT. Right now, I only have input VCFs where it is a mix of RSIDs and CHR:POS formats as the SNP ID. The files are completely the same other than the SNP IDs.

Let's say I have two imputation runs - Run A where SNP IDs are in the format CHR:POS:REF:ALT, and Run B where the SNP IDs are a mix. My question is, would I have to go back and standardize the SNP ID formats before imputation for both runs, or would the result be the same regardless? Does Minimac4 carry out imputation based on the SNP position and linkage only? I am wondering because the imputation takes a while and I would like to know if I would have to go back and re-impute the files.

Thanks!

**Comment by jonathonl** [comment]
The ID column will have no effect on the imputation. It will be copied over to the output VCF when the --rsid option is enabled. Otherwise the output file's ID column is populated with the CHR:POS:REF:ALT identifiers.

**Comment by jerrywzy** [comment]
Thanks!
