### ISSUE TITLE
Imputation aborted

### ISSUE THREAD

**Issue by albaicans** [statgen/Minimac4#46]
Hi,
I'm using Minimac4 for imputation with 1000 Genomes reference panel. While I could impute all other chromosomes successfully, I get this error when imputing chromosome 10:
"minimac4: /build/minimac4-1KJ7yD/minimac4-1.0.2/src/MarkovModel.cpp:1085: void MarkovModel::unfoldProbabilities(int, std::vector<float>&, std::vector<float>&, std::vector<float>&, int, std::vector<ReducedHaplotypeInfo>&, int): Assertion `adj_norec[i]<1e18' failed.
Aborted (core dumped)"
The reading of input file and reference panel file is done successfully, as well as chunking. The error happens when starting imputation.
Do you know what it means and how can I solve it?
Thank you very much,

Alba

**Comment by jonathonl** [comment]
This is fixed in the master branch. Please download from https://github.com/statgen/Minimac4/archive/refs/heads/master.zip

**Comment by albaicans** [comment]
Thank you, it works now!

**Comment by abiddanda54gene** [comment]
@jonathonl could this fix be tagged in a release build of `minimac4`? Its nice to have a tracked and working version that isn't just the current master branch if possible.

**Comment by jonathonl** [comment]
@abiddanda54gene, I just created a release: https://github.com/statgen/Minimac4/releases/tag/v1.0.3.
