### ISSUE TITLE
Invalid VCF for two chromosomes, running Minimac through The Michigan Imputation Server

### ISSUE THREAD

**Issue by julien-laval** [statgen/Minimac4#49]
Hello,

I am using the Michigan Imputation Server to phase VCFs with Minimac4.
Out of 22 chromosomes, 20 were phased successfully (and also successfully used for downstream analysis). However, 2 VCF files for 2 chromosomes are considered 'invalid' inputs and can't be phased. The given error is:
'File should be phased, but also includes unphased and/or missing genotypes! Please double-check!'
I am not sure to understand the meaning, but the VCF files were successfully checked by the package checkVCF (recommended by Michigan: https://github.com/zhanxw/checkVCF). There are no missing genotypes. I can't find any difference between my valid and invalid VCFs.

My invalid chromosomes are 9 and 15 but it seems random because with another dataset chromosomes 4, 12 and 15 are invalid.

Is this issue likely to come from Minimac4?

Thank you for your answer.

**Comment by jonathonl** [comment]
This is likely an error message from Imputation Sever's QC, not from Minimac4. Also, Minimac4 does not phase VCFs, but instead imputes already phased VCFs. Imputation Server uses Eagle to phase VCFs.

You should try emailing the Imputation Server help contact with your job ID so they can look into what is happening with your specific job.

**Comment by julien-laval** [comment]
Yes the QC is not passed.

Thank you for your time.
