### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by vanzod** [statgen/Minimac4#5]
Hello,

On your documentation you refer to the presence of a v1.0.0 release of Minimac4. However there are no releases listed here. Are you planning to release any soon?

Thank you

**Comment by Santy-8128** [comment]
Hi,

The one of github is version 1.0.0. The version number would be listed in
the following file and also be shown when you run the executable.

https://github.com/statgen/Minimac4/blob/master/CMakeLists.txt


*Regards,*
*Sayantan Das,*



*Post-Doctoral Fellow Department of BiostatisticsUniversity of Michigan,
Ann Arbor.MI 48109-2029*

**Comment by vanzod** [comment]
@Santy-8128 Thank you for following up on this. Unfortunately the absence of a version release policy would prevent us to make it available to our cluster users since we need to have a way to download the source archive from a predefined URL for each version.

Any chance you will transition to a more consistent versioning system?
