### ISSUE TITLE
Can't build from requirements.txt, zlib v1.2.11 no longer exists

### ISSUE THREAD

**Issue by sereeena** [statgen/Minimac4#50]
They have replaced it with v1.2.12. So to successfully build minimac4, the line in requirements.txt should be:   

zlib,https://zlib.net/zlib-1.2.12.tar.gz --hash sha256:91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9

**Comment by Alloyd21** [comment]
https://github.com/statgen/Minimac4/pull/51

**Comment by jonathonl** [comment]
I'm in the middle of merging major revisions into the master branch and cannot update the zlib URL right now. In the meantime, users can run `cget install zlib,http://zlib.net/fossils/zlib-1.2.11.tar.gz` before running `cget install -f ./requirements.txt`

**Comment by jonathonl** [comment]
Fixed with https://github.com/statgen/Minimac4/commit/3b8ddaa9cc68a7f46bdfb78b88a8558ed8fd6381. Thanks for reporting.
