### ISSUE TITLE
Imputing variants at multi-allelic sites

### ISSUE THREAD

**Issue by thheng** [statgen/Minimac4#52]
Hi,
Thanks for writing this wonderful software.
May I ask for your advice on using Minimac4 to impute variants at multi-allelic (MA) sites? 
Thank you very much!

**Comment by jonathonl** [comment]
Multiallelic variants should be split into multiple biallelic records (for both reference and target files). Indels should also be normalized between reference and target files.

**Comment by thheng** [comment]
Thank you for your reply. How does this affect interpretation as for MA sites the genotype aill be 0 in the entry for the other variant at that position since the reference panel does not accept missing data? Thanks

**Comment by jonathonl** [comment]
Yes, the interpretation is different. A `0|0` genotype would be interpreted as having zero occurrences of the alt allele, but not necessarily having two occurrences of the ref allele.

**Comment by thheng** [comment]
Thank you very much
