### ISSUE TITLE
lack of compliance with VCF v4.3 specification

### ISSUE THREAD

**Issue by freeseek** [statgen/Minimac4#58]
According to [v4.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf) of the VCF specification, the following reserved INFO and FORMAT fields should have a specified Number:
```
INFO/AC   Number=A
INFO/AF   Number=A
FORMAT/GP   Number=G
FORMAT/DS   Number=A
```
However in Minimac4 they get specified as:
```
INFO/AC   Number=1
INFO/AF   Number=1
FORMAT/GP   Number=3
FORMAT/DS   Number=1
```
This can cause problems with downstream software that expect the correct Number values

**Comment by jonathonl** [comment]
Fixed with https://github.com/statgen/Minimac4/commit/0b88de9d02522afc0d0886d42b5e64b4f5b548b6
