### ISSUE TITLE
The imputed vcf has far more genotypes than the target phased vcf and missed rsID.

### ISSUE THREAD

**Issue by huww1998** [statgen/Minimac4#60]
my target vcf:
![image](https://github.com/statgen/Minimac4/assets/81839560/3239f0fc-6ef6-4557-a525-58c6a92d9741)
imputed vcf: 
![image](https://github.com/statgen/Minimac4/assets/81839560/a127e32b-ae36-46ef-bc2b-1beb94032cc9)

Before using minimac v4.1.2, my target vcf file has been phased by SHAPEIT2. I also used `--all-typed-sites`, but I think it doesn't work. After I checked the  target vcf(only included chr 1), it has 19,020 variants. But the imputed vcf has  unexpectedly 3,752,110 variants. My Reference Panel is **1000 Genomes Phase 3** downloaded from [1000 Genomes Phase 3 (version 5)](https://genome.sph.umich.edu/wiki/Minimac4#Reference_Panels_for_Download). I used `1.1000g.Phase3.v5.With.Parameter.Estimates.m3vcf.gz` as Reference Panel when I imputed the chr 1. The command are displayed below. 
![image](https://github.com/statgen/Minimac4/assets/81839560/48457466-aaa7-4852-baba-cfe374eafe5c)
Besides, I also tried to subset the imputed vcf file by using the `chr::pos`  information from my target vcf. But it got 33,019 variants compared with 19,020 variants in the orginal target vcf. The result makes me very confused. I don't know what problem is. 
Another problem is the rsID missing in the imputed vcf file. Maybe I should set the `--sites` , `--min-r2` or other parameters to solve these problems?

**Comment by jonathonl** [comment]
Can you clarify what you believe is wrong with the results you are getting? 3,752,110 variants seems reasonable for 1000g chromosome 1. Note that, in addition to imputing missing genotypes, Minimac also imputes variants that exist in the reference panel but not in the target VCF.

**Comment by jonathonl** [comment]
The ID column in the imputed results comes from the reference panel. The reference panel you are using isn't annotated with rsID's but instead uses {chrom}:{pos} as the identifier.
