### ISSUE TITLE
Error: failed writing output

### ISSUE THREAD

**Issue by andrei-barysenka** [statgen/Minimac4#70]
I was trying to use minimac4 (precompiled, OS: Ubuntu 20.04 ) to run imputation on 55000 samples, here is the command line:

minimac4 --region 1:40000000-60000000 --overlap 500000 
--output ./imputed.55k.dose.vcf.gz --output-format vcf.gz --format GT,DS,GP,HDS --min-ratio 0.00001 --decay 0 
--all-typed-sites --sites imputed.55k.info --threads 20 
--empirical-output ./imputed.55k.empiricalDose.vcf.gz 
--map ~/1000g-phase-3-v5/2.0.1/map/genetic_map_hg19_withX.txt.gz 
~/1000g-phase-3-v5/2.0.1/msav/1.1000g.Phase3.v5.With.Parameter.Estimates.msav 
../eagle/phased.55k.vcf.gz 
--temp-prefix /mnt/storage/temp/mm4_

After a while I get this error message (skipped some lines at the beginning of the output):

...
Completed 49800 of 55000 samples                           
Completed 50000 of 55000 samples                  
Completed 50200 of 55000 samples                      
Completed 50400 of 55000 samples                  
Completed 50600 of 55000 samples                            
Error: index file too big for skippable zstd frame       
Error: could not append S1R index                           
Completed 50800 of 55000 samples                           
Error: index file too big for skippable zstd frame            
Error: could not append S1R index                             
Completed 51000 of 55000 samples                              
Error: index file too big for skippable zstd frame            
Error: could not append S1R index                                                                                             
Error: index file too big for skippable zstd frame                                                                            
Error: could not append S1R index                                                                                             
Unsupported file format                                                                                                       
Completed 51200 of 55000 samples                                                                                              
Error: index file too big for skippable zstd frame
Error: could not append S1R index               
Error: index file too big for skippable zstd frame
Error: could not append S1R index                        
Unsupported file format                                        
Completed 51400 of 55000 samples   
Error: index file too big for skippable zstd frame
Error: could not append S1R index
Error: index file too big for skippable zstd frame
Error: could not append S1R index
Unsupported file format                                        
Error: failed writing output                                   
Error: index file too big for skippable zstd frame 
Error: could not append S1R index                                                                                             
Error: index file too big for skippable zstd frame
Error: could not append S1R index

Directory in the --temp-prefix option has several TB of free space

Do you have an idea what might cause this ?

**Comment by jonathonl** [comment]
That looks like a disk write error to me. Is /mnt/storage/temp/ a network filesystem? How long did it take to get to 50600 samples completed? I'm curious if you ran again if it would fail at the same place. 

Does ../eagle/phased.55k.vcf.gz contain array data?

**Comment by andrei-barysenka** [comment]
Hi,

/mnt/storage/temp/ is local filesystem; it took approx. 25 min until the error message appeared. The phased.55k.vcf.gz contains array data (UKB data); running minimac4 again using the same input produces exact same error messages at the same sample number mark.

**Comment by andrei-barysenka** [comment]
ok, it seems minimac4 is hitting the soft limit of open file descriptors when the error occurs

**Comment by jonathonl** [comment]
Ok, good catch. Thanks for reporting back. I need to fix the error messaging to be more informative.

If you ever hit a hard limit, you could increase the `--temp-buffer` size, which would use more RAM but fewer temp files. Or you could split samples into batches and run as separate processes, then merge with https://github.com/statgen/hds-util. 

I would also recommend only exporting HDS, since the other three format fields can be generated from HDS with https://github.com/statgen/hds-util if/when needed. Doing so will save you disk space.

**Comment by andrei-barysenka** [comment]
Thank you for the advise, will look into it !
